spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
    show-sql: true

fcm:
  private-key: bottler-fcm.json

jwt:
  secret: ${JWT_SECRET_KEY}  # JWT 비밀 키
  access:
    token:
      expiration: 1800000  # 액세스 토큰 유효 시간 (30분)
  #      expiration: 10000  # 액세스 토큰 유효 시간 (10초)
  refresh:
    token:
      expiration: 604800000  # 리프레시 토큰 유효 시간 (7일)
