spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      validation-timeout: 2000
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE


fcm:
  private-key: ${BOTTLER_FCM_BASE64}

jwt:
  secret: ${JWT_SECRET_KEY}  # JWT 비밀 키
  access:
    token:
      expiration: 3600000  # 액세스 토큰 유효 시간 (1시간)
  #      expiration: 10000  # 액세스 토큰 유효 시간 (10초)
  refresh:
    token:
      expiration: 604800000  # 리프레시 토큰 유효 시간 (7일)

mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL_USER_NAME}
  password: ${EMAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
  redirect:
    url: ${KAKAO_REDIRECT_URL}

slack:
  token: ${SLACK_TOKEN}
