version: '3.8'

services:
  app:
    image: ${ECR_URI}/bottler-backend:${TAG}
    container_name: app-server
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BOTTLER_FCM_BASE64=${BOTTLER_FCM_BASE64}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - ECR_URI=${ECR_URI}
      - BUCKET_NAME=${BUCKET_NAME}
      - BASE_URL=${BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
