services:
  app:
    image: ${DOCKER_USERNAME}/bottler:${TAG}  # Docker Hub 이미지 사용
    container_name: app-server
    ports:
      - "80:8080"  # 컨테이너 포트를 8080으로 노출
      - "9092:9092"
    env_file: # 환경 변수 파일(.env) 참조
      - .env
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - TZ:Asia/Seoul
    restart: always  # 재시작 정책 추가

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always  # 재시작 정책 추가

volumes:
  redis_data: