services:
  app:
    image: ${DOCKER_USERNAME}/bottler:${TAG}  # Docker Hub 이미지 사용
    container_name: app-server
    ports:
      - "8080:8080"  # 컨테이너 포트를 8080으로 노출
    env_file:        # 환경 변수 파일(.env) 참조
      - .env
